### ISSUE TITLE
require json is not working

### ISSUE THREAD

**Issue by algiuxass** [neonious/lowjs#114] opened 2020-07-09 13:31 UTC
Example from avj node module:
```js
var metaSchema = require('./refs/json-schema-draft-07.json');
```
```
TypeError: cannot resolve module './refs/json-schema-draft-07.json', parent '..../node_modules/ajv/lib/definition_schema.js'
```

Make it possible to require json files.

**Comment by neoniousTR** [comment] 2020-07-13 14:41
low.js should support requiring JSON files. I will try myself next weekend and report!

**Comment by neoniousTR** [comment] 2020-07-19 13:26
Requiring JSON files works perfectly. I guess the problem is the "..../" instead of a "../../", so the resolving has some kind of bug. Do you have an example project or steps to do to trigger such an error?

**Comment by algiuxass** [comment] 2020-07-29 04:37
Sorry, forgot to mention the "...." was to hide full path or whatever was it. It's shouldn't be a problem now. Thanks!

**Closed** 2020-09-27 10:12 UTC
